// Tier definitions shared by client components, server routes, and middleware.
// No "use client" / Node-only imports here — must stay Edge-runtime safe.

export type Tier = "free" | "premium" | "pro";

export const TIER_RANK: Record<Tier, number> = { free: 0, premium: 1, pro: 2 };

// Minimum tier required per route (mapped from PRD §8 permissions).
export const ROUTE_MIN_TIER: Record<string, Tier> = {
  "/": "free",
  "/chart": "free",
  "/technical": "premium",
  "/indicators": "premium",
  "/plan": "premium",
  "/risk": "premium",
  "/levels": "premium",
  "/correlation": "pro",
  "/smc": "pro",
  "/whatif": "pro",
  "/portfolio": "pro",
  "/alerts": "pro",
  "/chat": "pro",
  "/content": "pro",
  "/calendar": "premium",
  "/journal": "premium",
  "/ea-builder": "pro",
  "/backtest": "pro",
  "/ai-ea":        "pro",
  "/sr-indicator": "pro",
  "/cme-oi":       "pro",
  "/ea-monitor":   "pro",
  "/ai-model":         "pro",
  "/ai-model/history": "pro",
  "/trade-ideas":      "pro",
  "/market-regime":   "premium",
  "/forecast":        "pro",
  "/patterns":        "premium",
  "/sessions":        "premium",
  "/volatility":      "premium",
  "/seasonality2":    "pro",
  "/fibonacci":       "premium",
  "/econ-impact":     "premium",
  "/momentum":        "premium",
  "/trend-strength":  "premium",
  "/news-sentiment":  "premium",
  "/pivots":          "premium",
  "/dxy-correlation": "premium",
  "/fear-greed":      "premium",
  "/market-summary":  "premium",
  "/supply-demand":   "premium",
  "/roc":                  "premium",
  "/intermarket-heatmap":  "premium",
  "/scalp-levels":         "premium",
  "/macro-score":          "premium",
  "/range-forecast":       "pro",
  "/options-flow":         "pro",
  "/weekly-brief":        "premium",
  "/mining-stocks":       "premium",
  "/gold-calendar":       "premium",
  "/position-calc":       "free",
  "/breakout-scanner":    "premium",
  "/silver-ratio":        "premium",
  "/price-heatmap":       "premium",
  "/elliott-wave":        "pro",
  "/commodity-matrix":    "premium",
  "/yield-curve":         "premium",
  "/geo-risk":            "premium",
  "/cb-tracker":          "premium",
  "/funding-rates":       "premium",
  "/etf-flows":           "premium",
  "/sentiment-dashboard": "premium",
  "/leaderboard":         "free",
  "/rate-watch":          "premium",
  "/inflation-tracker":   "premium",
  "/mining-cost":         "premium",
  "/gold-oil-ratio":      "premium",
  "/money-supply":        "premium",
  "/gold-demand":         "premium",
  "/macro-heat":          "premium",
  "/options-expiry":      "pro",
  "/gold-supply":         "premium",
  "/dxy-breakdown":       "premium",
  "/trade-flow":          "premium",
  "/crypto-gold":         "premium",
  "/macro-scenario":      "pro",
  "/trade-grade":         "pro",
  "/market-breadth":      "premium",
  "/gold-beta":           "premium",
  "/risk-signals":        "premium",
  "/divergence-scan":     "pro",
  "/flow-tracker":        "premium",
  "/news-impact":         "premium",
  "/gold-cycle":          "premium",
  "/liquidity-map":       "free",
  "/smart-money":         "pro",
  "/carry-trade":         "premium",
  "/volatility-term":    "pro",
  "/gold-currencies":      "premium",
  "/volume-profile":       "premium",
  "/gold-sp500":           "premium",
  "/miner-ratio":          "premium",
  "/global-yields":        "premium",
  "/position-dashboard":   "premium",
  "/copper-gold":          "premium",
  "/fair-value":           "pro",
  "/gold-structure":       "premium",
  "/gold-bonds":           "premium",
  "/fear-index":           "premium",
  "/momentum-composite":   "pro",
  "/gold-volatility":      "pro",
  "/relative-strength":    "premium",
  "/etf-positioning":      "premium",
  "/risk-parity":         "pro",
  "/macro-dashboard":     "pro",
  "/gold-cycle-clock":    "premium",
  "/futures-curve":       "premium",
  "/cot-extremes":        "premium",
  "/hurst-analysis":      "pro",
  "/market-internals":    "premium",
  "/seasonality-detail":  "premium",
  "/position-heat":       "pro",
  "/multi-momentum":      "premium",
  "/drawdown-tracker":    "premium",
  "/asia-premium":        "premium",
  "/macro-drivers":       "pro",
  "/options-gamma":       "pro",
  "/event-study":         "premium",
  "/vix-regime":          "premium",
  "/gold-breakeven":      "premium",
  "/gold-ownership":      "free",
  "/currency-stress":     "premium",
  "/fed-dot-plot":        "premium",
  "/comex-vault":         "premium",
  "/yield-spread":        "premium",
  "/gold-leverage":       "pro",
  "/admin":               "pro",
  "/brief":   "pro",
  "/scanner":     "premium",
  "/seasonality": "pro",
  "/paper":       "free",
  "/news":        "premium",
};

export function minTierFor(route: string): Tier {
  return ROUTE_MIN_TIER[route] ?? "free";
}

export function canAccess(tier: Tier, route: string): boolean {
  return TIER_RANK[tier] >= TIER_RANK[minTierFor(route)];
}
