import { NextResponse } from "next/server";
import { geminiEnabled } from "@/lib/gemini";
import type { BacktestConfig, BacktestStrategyType } from "@/lib/backtest";

export const dynamic = "force-dynamic";

function buildPrompt(strategy: BacktestStrategyType, params: Partial<BacktestConfig>, stats: {
  profitFactor: number; winRate: number; maxDrawdown: number; sharpeRatio: number; totalTrades: number;
}): string {
  const paramStr = JSON.stringify(params, null, 2);
  const sl = params.slPoints ?? 20;
  const tp = params.tpPoints ?? 40;

  return `You are an expert MQL5 developer. Generate a complete, compilable Expert Advisor (.mq5 file) for MetaTrader 5.

STRATEGY: ${strategy}
OPTIMIZED PARAMETERS:
${paramStr}

BACKTEST RESULTS (on XAUUSD D1, 2 years):
- Profit Factor: ${stats.profitFactor.toFixed(2)}
- Win Rate: ${stats.winRate.toFixed(1)}%
- Max Drawdown: ${stats.maxDrawdown.toFixed(1)}%
- Sharpe Ratio: ${stats.sharpeRatio.toFixed(2)}
- Total Trades: ${stats.totalTrades}

REQUIREMENTS:
1. EA name: "GIOS_${strategy.toUpperCase()}_EA"
2. Magic number: 20240101
3. Input parameters must include (with exact values as defaults from optimized params):
   - Lot size (default 0.01)
   - Stop Loss in USD/points (${sl})
   - Take Profit in USD/points (${tp})
   - All strategy-specific parameters from above
4. Use OnTick() for signal detection
5. Implement proper position management (one trade at a time, check magic number)
6. Add comments explaining logic
7. Add input for Maximum Spread check (default 30 points)
8. Add time filter inputs (StartHour, EndHour defaults 0-23 = always)
9. Implement the EXACT strategy logic for "${strategy}":
   - ema_cross: fast EMA crosses above/below slow EMA
   - triple_ema: price > mid > slow for BUY, price < mid < slow for SELL (with fast EMA confirmation)
   - rsi: RSI crosses above OS level for BUY, crosses below OB level for SELL
   - macd: MACD line crosses above signal for BUY, below for SELL
   - bb_bounce: price touches lower band for BUY, upper band for SELL
   - price_ema: price crosses above EMA for BUY, below for SELL
10. Include error handling for order placement
11. The EA must compile without errors in MQL5

Return ONLY the complete .mq5 source code, starting with //+------------------------------------------------------------------+`;
}

function buildFallbackEA(strategy: BacktestStrategyType, params: Partial<BacktestConfig>): string {
  const sl = params.slPoints ?? 20;
  const tp = params.tpPoints ?? 40;
  const fast = params.fastPeriod ?? 9;
  const slow = params.slowPeriod ?? 50;
  const rsiPeriod = params.rsiPeriod ?? 14;
  const rsiOS = params.rsiOS ?? 30;
  const rsiOB = params.rsiOB ?? 70;

  return `//+------------------------------------------------------------------+
//|  GIOS_${strategy.toUpperCase()}_EA.mq5                                              |
//|  Generated by Gold Intelligence OS                                   |
//|  Strategy: ${strategy}                                               |
//+------------------------------------------------------------------+
#property copyright "EA Profit Lab / Gold Intelligence OS"
#property version   "1.00"
#property strict

//--- Input Parameters
input double InpLotSize    = 0.01;   // Lot Size
input double InpStopLoss   = ${sl};    // Stop Loss (USD)
input double InpTakeProfit = ${tp};    // Take Profit (USD)
input int    InpFastPeriod = ${fast};    // Fast EMA Period
input int    InpSlowPeriod = ${slow};   // Slow EMA Period
input int    InpRsiPeriod  = ${rsiPeriod};    // RSI Period
input double InpRsiOS      = ${rsiOS};    // RSI Oversold Level
input double InpRsiOB      = ${rsiOB};    // RSI Overbought Level
input int    InpMagic      = 20240101; // Magic Number
input int    InpMaxSpread  = 30;      // Max Spread (points)
input int    InpStartHour  = 0;       // Start Hour (0-23)
input int    InpEndHour    = 23;      // End Hour (0-23)

//+------------------------------------------------------------------+
//| Expert initialization function                                     |
//+------------------------------------------------------------------+
int OnInit() {
   Print("GIOS EA initialized. Strategy: ${strategy}");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Check if within trading hours                                      |
//+------------------------------------------------------------------+
bool IsTradingTime() {
   int hour = TimeHour(TimeCurrent());
   return (hour >= InpStartHour && hour <= InpEndHour);
}

//+------------------------------------------------------------------+
//| Count open positions with our magic number                         |
//+------------------------------------------------------------------+
int CountPositions() {
   int count = 0;
   for (int i = PositionsTotal() - 1; i >= 0; i--) {
      if (PositionGetSymbol(i) == Symbol() && PositionGetInteger(POSITION_MAGIC) == InpMagic)
         count++;
   }
   return count;
}

//+------------------------------------------------------------------+
//| Open order helper                                                  |
//+------------------------------------------------------------------+
void OpenOrder(ENUM_ORDER_TYPE type) {
   if (CountPositions() > 0) return;

   double spread = SymbolInfoInteger(Symbol(), SYMBOL_SPREAD) * Point();
   if (spread > InpMaxSpread * Point()) return;

   double price  = (type == ORDER_TYPE_BUY) ? SymbolInfoDouble(Symbol(), SYMBOL_ASK) : SymbolInfoDouble(Symbol(), SYMBOL_BID);
   double sl     = (type == ORDER_TYPE_BUY) ? price - InpStopLoss : price + InpStopLoss;
   double tp     = (type == ORDER_TYPE_BUY) ? price + InpTakeProfit : price - InpTakeProfit;

   MqlTradeRequest req = {};
   MqlTradeResult  res = {};
   req.action   = TRADE_ACTION_DEAL;
   req.symbol   = Symbol();
   req.volume   = InpLotSize;
   req.type     = type;
   req.price    = price;
   req.sl       = NormalizeDouble(sl, Digits());
   req.tp       = NormalizeDouble(tp, Digits());
   req.magic    = InpMagic;
   req.comment  = "GIOS_${strategy}";

   if (!OrderSend(req, res))
      Print("OrderSend failed: ", GetLastError());
}

//+------------------------------------------------------------------+
//| Expert tick function                                               |
//+------------------------------------------------------------------+
void OnTick() {
   if (!IsTradingTime()) return;
   if (!IsNewBar()) return;  // Signal check once per bar

   // --- Indicator values ---
   double fastEMA[], slowEMA[], rsiVal[];
   ArraySetAsSeries(fastEMA, true);
   ArraySetAsSeries(slowEMA, true);
   ArraySetAsSeries(rsiVal, true);

   int hFast = iEMA(Symbol(), PERIOD_D1, InpFastPeriod, 0, PRICE_CLOSE);
   int hSlow = iEMA(Symbol(), PERIOD_D1, InpSlowPeriod, 0, PRICE_CLOSE);
   int hRsi  = iRSI(Symbol(), PERIOD_D1, InpRsiPeriod, PRICE_CLOSE);

   CopyBuffer(hFast, 0, 0, 3, fastEMA);
   CopyBuffer(hSlow, 0, 0, 3, slowEMA);
   CopyBuffer(hRsi,  0, 0, 3, rsiVal);

   bool buySignal  = (fastEMA[1] > slowEMA[1] && fastEMA[2] <= slowEMA[2]);
   bool sellSignal = (fastEMA[1] < slowEMA[1] && fastEMA[2] >= slowEMA[2]);

   if (buySignal)  OpenOrder(ORDER_TYPE_BUY);
   if (sellSignal) OpenOrder(ORDER_TYPE_SELL);
}

//+------------------------------------------------------------------+
//| New bar detection                                                  |
//+------------------------------------------------------------------+
datetime lastBar = 0;
bool IsNewBar() {
   datetime current = iTime(Symbol(), PERIOD_D1, 0);
   if (current != lastBar) { lastBar = current; return true; }
   return false;
}
`;
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { strategy, params, stats } = body as {
      strategy: BacktestStrategyType;
      params:   Partial<BacktestConfig>;
      stats:    { profitFactor: number; winRate: number; maxDrawdown: number; sharpeRatio: number; totalTrades: number };
    };

    let code: string;

    if (geminiEnabled()) {
      try {
        const MODEL   = process.env.GEMINI_MODEL ?? "gemini-2.5-flash";
        const API_KEY = process.env.GEMINI_API_KEY!;
        const url     = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`;
        const res2    = await fetch(url, {
          method: "POST",
          headers: { "x-goog-api-key": API_KEY, "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [{ parts: [{ text: buildPrompt(strategy, params, stats) }] }],
            generationConfig: { temperature: 0.2, thinkingConfig: { thinkingBudget: 0 } },
          }),
          signal: AbortSignal.timeout(60_000),
        });
        const json2 = await res2.json();
        const raw   = json2?.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
        // Strip markdown code fences if Gemini wraps it
        code = raw.replace(/^```(?:mql5|cpp|c\+\+)?\n?/, "").replace(/\n?```$/, "").trim();
        if (!code.startsWith("//")) code = buildFallbackEA(strategy, params);
      } catch {
        code = buildFallbackEA(strategy, params);
      }
    } else {
      code = buildFallbackEA(strategy, params);
    }

    const filename = `GIOS_${strategy.toUpperCase()}_EA.mq5`;
    return NextResponse.json({ ok: true, code, filename });
  } catch (e) {
    return NextResponse.json({ ok: false, error: String(e) }, { status: 500 });
  }
}
