"use client";

import { useCallback, useEffect, useState } from "react";
import type { DailyBrief } from "@/lib/gemini";
import { PageHeader } from "@/components/PageHeader";
import { Disclaimer } from "@/components/Disclaimer";
import { useI18n } from "@/lib/i18n";

// ── Bias badge ────────────────────────────────────────────────────────────────

function BiasBadge({ bias, confidence }: { bias: string; confidence: string }) {
  const colors = {
    bullish: "border-emerald-500/60 bg-emerald-500/15 text-emerald-400",
    bearish: "border-red-500/60 bg-red-500/15 text-red-400",
    neutral: "border-amber-500/60 bg-amber-500/15 text-amber-400",
  };
  const icons = { bullish: "📈", bearish: "📉", neutral: "➡️" };
  const labels = { bullish: "Bullish", bearish: "Bearish", neutral: "Neutral" };
  const key = (bias in colors ? bias : "neutral") as keyof typeof colors;
  const confColors = { high: "text-emerald-400", medium: "text-amber-400", low: "text-red-400" };
  return (
    <div className="flex items-center gap-2">
      <span className={`flex items-center gap-1.5 rounded-full border px-3 py-1 text-sm font-bold ${colors[key]}`}>
        {icons[key]} {labels[key]}
      </span>
      <span className={`text-xs font-medium ${confColors[confidence as keyof typeof confColors] ?? "text-silver/50"}`}>
        {confidence === "high" ? "High confidence" : confidence === "medium" ? "Med confidence" : "Low confidence"}
      </span>
    </div>
  );
}

// ── Section card ──────────────────────────────────────────────────────────────

function SectionCard({ section, lang }: { section: DailyBrief["sections"][0]; lang: "th" | "en" }) {
  const [open, setOpen] = useState(true);
  const title   = lang === "th" ? section.titleTh   : section.title;
  const content = lang === "th" ? section.contentTh : section.content;

  return (
    <div className="panel overflow-hidden">
      <button
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center gap-2.5 px-4 py-3 text-left hover:bg-white/[0.02] transition-colors"
      >
        <span className="text-xl leading-none">{section.icon}</span>
        <span className="flex-1 text-sm font-semibold text-silver">{title}</span>
        <span className="text-silver/30 text-xs">{open ? "▲" : "▼"}</span>
      </button>
      {open && (
        <div className="border-t border-base-border/40 px-4 pb-4 pt-3">
          <p className="text-sm leading-relaxed text-silver/80 whitespace-pre-line">{content}</p>
        </div>
      )}
    </div>
  );
}

// ── Price metric ──────────────────────────────────────────────────────────────

function PriceBanner({ brief }: { brief: DailyBrief }) {
  const chPos = brief.change >= 0;
  return (
    <div className="panel p-4 sm:p-5">
      <div className="flex flex-wrap items-center gap-4 justify-between">
        <div>
          <div className="text-[11px] uppercase tracking-widest text-silver/40 mb-1">XAUUSD · Gold Futures</div>
          <div className="flex items-baseline gap-3">
            <span className="text-3xl font-bold font-mono text-gold">${brief.price.toFixed(2)}</span>
            <span className={`text-lg font-mono font-semibold ${chPos ? "text-emerald-400" : "text-red-400"}`}>
              {chPos ? "+" : ""}{brief.change.toFixed(2)} ({chPos ? "+" : ""}{brief.changePct.toFixed(2)}%)
            </span>
          </div>
        </div>
        <BiasBadge bias={brief.bias} confidence={brief.confidence} />
      </div>
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function BriefPage() {
  const { lang } = useI18n();
  const [brief, setBrief]     = useState<DailyBrief | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState("");
  const [lastFetch, setLastFetch] = useState<Date | null>(null);

  const fetchBrief = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/brief");
      const data = await res.json();
      if (!res.ok || data.error) throw new Error(data.error ?? "Failed");
      setBrief(data as DailyBrief);
      setLastFetch(new Date());
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load brief");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchBrief(); }, [fetchBrief]);

  const l = lang as "th" | "en";

  return (
    <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8">
      <PageHeader
        title={l === "th" ? "AI Daily Brief" : "AI Daily Brief"}
        subtitle={l === "th"
          ? "รายงานตลาดทองคำประจำวัน สร้างโดย Gemini AI จากข้อมูล live"
          : "Daily gold market report generated by Gemini AI from live data"}
      />

      {/* Toolbar */}
      <div className="mb-4 flex items-center justify-between">
        <div className="text-[11px] text-silver/40">
          {lastFetch && `อัปเดต ${lastFetch.toLocaleTimeString("th-TH")} · cache 1 ชั่วโมง`}
        </div>
        <button
          onClick={fetchBrief}
          disabled={loading}
          className={`flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium transition-colors
            ${loading ? "opacity-50 border-base-border text-silver/30" : "border-gold/40 text-gold hover:bg-gold/10"}`}
        >
          {loading ? (
            <span className="inline-block h-3 w-3 animate-spin rounded-full border-2 border-gold/30 border-t-gold" />
          ) : "🔄"}
          {loading ? (l === "th" ? "กำลังสร้าง…" : "Generating…") : (l === "th" ? "รีเฟรช" : "Refresh")}
        </button>
      </div>

      {/* Loading skeleton */}
      {loading && !brief && (
        <div className="space-y-4 animate-pulse">
          <div className="panel p-5 h-24 bg-base-panel/60" />
          <div className="panel p-4 h-16 bg-base-panel/40" />
          {[1,2,3,4,5,6].map((i) => (
            <div key={i} className="panel p-4 h-28 bg-base-panel/30" />
          ))}
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-400">
          <strong>เกิดข้อผิดพลาด:</strong> {error}
          <br /><span className="text-xs opacity-70">ตรวจสอบ Gemini API key ใน .env.local</span>
        </div>
      )}

      {/* Brief content */}
      {brief && (
        <div className="space-y-4">
          {/* Price banner */}
          <PriceBanner brief={brief} />

          {/* Date + headline */}
          <div className="panel p-4 sm:p-5 border-gold/20 bg-gradient-to-br from-gold/5 to-transparent">
            <div className="text-[11px] uppercase tracking-widest text-gold/60 mb-2">{brief.date}</div>
            <h2 className="text-xl font-bold text-silver mb-3 leading-snug">
              {l === "th" ? brief.headlineTh : brief.headline}
            </h2>
            <p className="text-sm text-silver/70 leading-relaxed">
              {l === "th" ? brief.summaryTh : brief.summary}
            </p>
          </div>

          {/* 6 section cards */}
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {brief.sections.map((sec) => (
              <SectionCard key={sec.id} section={sec} lang={l} />
            ))}
          </div>

          {/* Footer meta */}
          <div className="rounded-xl border border-base-border/30 bg-base-panel/30 px-4 py-3 flex flex-wrap gap-4 text-[11px] text-silver/35">
            <span>🤖 Gemini AI · {new Date(brief.generatedAt).toLocaleString("th-TH")}</span>
            <span>📊 Data: Yahoo Finance GC=F + ForexFactory</span>
            <span className={`font-medium ${brief.confidence === "high" ? "text-emerald-400/60" : brief.confidence === "medium" ? "text-amber-400/60" : "text-red-400/60"}`}>
              Confidence: {brief.confidence}
            </span>
          </div>

          <Disclaimer />
        </div>
      )}
    </div>
  );
}
